apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/client-name: gcloud
    run.googleapis.com/client-version: 517.0.0
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/operation-id: 30a1216d-4331-480c-a784-9d04ba04558c
    run.googleapis.com/urls: '["https://directus-test-812872501910.asia-southeast1.run.app","https://directus-test-pfne2mqwja-as.a.run.app"]'
    serving.knative.dev/creator: nmhuyen@gmail.com
    serving.knative.dev/lastModifier: nmhuyen@gmail.com
  creationTimestamp: '2025-11-26T07:39:42.445790Z'
  generation: 6
  labels:
    cloud.googleapis.com/location: asia-southeast1
    run.googleapis.com/satisfiesPzs: 'true'
  name: directus-test
  namespace: '812872501910'
  resourceVersion: AAZF+WApMt8
  selfLink: /apis/serving.knative.dev/v1/namespaces/812872501910/services/directus-test
  uid: 550eae6a-2116-4ae5-8382-20dc53ca50c0
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '5'
        autoscaling.knative.dev/minScale: '0'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 517.0.0
        run.googleapis.com/cloudsql-instances: github-chatgpt-ggcloud:asia-southeast1:mysql-directus-web-test
        run.googleapis.com/cpu-throttling: 'false'
        run.googleapis.com/sessionAffinity: 'false'
      labels:
        client.knative.dev/nonce: rebdwquqgi
        run.googleapis.com/startupProbeType: Custom
    spec:
      containerConcurrency: 80
      containers:
      - env:
        - name: DB_CLIENT
          value: mysql
        - name: DB_HOST
          value: localhost
        - name: DB_PORT
          value: '3306'
        - name: DB_SOCKET_PATH
          value: /cloudsql/github-chatgpt-ggcloud:asia-southeast1:mysql-directus-web-test
        - name: DB_DATABASE
          value: directus
        - name: DB_USER
          value: directus
        - name: ADMIN_EMAIL
          value: admin@example.com
        - name: PUBLIC_URL
          value: https://directus-test-812872501910.asia-southeast1.run.app
        - name: WEBSOCKETS_ENABLED
          value: 'true'
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: latest
              name: DIRECTUS_DB_PASSWORD_test
        - name: KEY
          valueFrom:
            secretKeyRef:
              key: latest
              name: DIRECTUS_KEY_test
        - name: SECRET
          valueFrom:
            secretKeyRef:
              key: latest
              name: DIRECTUS_SECRET_test
        - name: RESTART_TRIGGER
          value: '1764230673'
        - name: DB_AUTH_FIX_TRIGGER
          value: '1764241312'
        - name: DB_USER_RECOVERY_TRIGGER
          value: '1764241396'
        - name: KNOWN_PASSWORD_TRIGGER
          value: '1764241627'
        - name: CORS_ENABLED
          value: 'true'
        - name: CORS_ORIGIN
          value: https://github-chatgpt-ggcloud.web.app
        - name: CORS_METHODS
          value: GET,POST,PUT,PATCH,DELETE,OPTIONS
        - name: CORS_ALLOWED_HEADERS
          value: Content-Type,Authorization
        - name: CORS_CREDENTIALS
          value: 'true'
        image: directus/directus:11.2.2
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /server/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          failureThreshold: 15
          httpGet:
            path: /server/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
      serviceAccountName: chatgpt-deployer@github-chatgpt-ggcloud.iam.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
status:
  address:
    url: https://directus-test-pfne2mqwja-as.a.run.app
  conditions:
  - lastTransitionTime: '2025-12-15T08:27:02.749919Z'
    status: 'True'
    type: Ready
  - lastTransitionTime: '2025-12-15T08:26:28.444849Z'
    status: 'True'
    type: ConfigurationsReady
  - lastTransitionTime: '2025-12-15T08:27:02.711244Z'
    status: 'True'
    type: RoutesReady
  latestCreatedRevisionName: directus-test-00006-kwm
  latestReadyRevisionName: directus-test-00006-kwm
  observedGeneration: 6
  traffic:
  - latestRevision: true
    percent: 100
    revisionName: directus-test-00006-kwm
  url: https://directus-test-pfne2mqwja-as.a.run.app
