name: Terraform Deploy

on:
  push:
    branches: [main]
    paths:
      - 'terraform/**'
  pull_request:
    branches: [main]
    paths:
      - 'terraform/**'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  actions: read

jobs:
  terraform:
    uses: Huyen1974/platform-infra/.github/workflows/terraform-apply.yml@v1.0.0
    with:
      project_id: github-chatgpt-ggcloud
      service_account: chatgpt-deployer@github-chatgpt-ggcloud.iam.gserviceaccount.com
      workload_identity_provider: projects/812872501910/locations/global/workloadIdentityPools/agent-data-pool/providers/github-provider
      terraform_directory: ./terraform
      backend_bucket: huyen1974-web-test-tfstate
      backend_prefix: terraform/state
      terraform_version: "1.9.0"
      auto_apply: false
